image: nettreksl/alpine-node-ssh-chrome:1.2.0

variables:
  DIST_PATH: "dist/shift-planning"
  DOC_PATH: "documentation"
  SASSDOC_PATH: "sassdoc"
  COVERAGE_PATH: "coverage"
  KARMA_RES_PATH: "karma/shift-planning/test-results.xml"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - test
  - build
  - deploy

lint:
  stage: test
  script:
    - npm run lint

unit test:
  stage: test
  script:
    - npm run test:ci
  artifacts:
    paths:
      - $COVERAGE_PATH/*
      - $KARMA_RES_PATH
    reports:
      junit: $KARMA_RES_PATH
  coverage: '/(\d*.?\d+)%/'

e2e test:
  stage: test
  script:
    - npm run e2e:ci

build staging:
  stage: build
  except:
    - tags
  dependencies: []
  script:
    - npm run build:prod
  artifacts:
    name: $CI_JOB_NAME-$CI_COMMIT_REF_NAME
    paths:
      - $DIST_PATH/*
    expire_in: 3 days

build release:
  stage: build
  only:
    - tags
  dependencies: []
  script:
    - echo "{\"version\":\"$CI_COMMIT_TAG\",\"hash\":\"$CI_COMMIT_SHA\",\"date\":\"$(date +"%Y-%m-%d")\"}" > "./meta.json"
    - npm run build:prod
    - npm run document
  artifacts:
    name: release-$CI_COMMIT_REF_NAME
    paths:
      - $DIST_PATH/*
      - $DOC_PATH/*
      - $SASSDOC_PATH/*
      - meta.json
    expire_in: 30 days

deploy staging:
  stage: deploy
  only:
    - develop
  dependencies:
    - build staging
  script:
    - node ./ci_scripts/upload.js "$DIST_PATH/" "$FTP_STAGING_HOST" "$FTP_STAGING_USER" "$FTP_STAGING_PASS"

deploy release:
  stage: deploy
  only:
    - tags
  when: manual
  dependencies:
    - build release
  script:
    - node ./ci_scripts/upload.js "$DIST_PATH/" "$FTP_PROD_HOST" "$FTP_PROD_USER" "$FTP_PROD_PASS"

# automatic deploy the documentation as gitlab page - needs to be activated
#pages:
#  stage: deploy
#  only:
#    - tags
#  except:
#    - /^(?!master).+@/
#  dependencies:
#    - build release
#  script:
#    - mkdir public
#    - cp -r $DOC_PATH/* public
#    - cp -r $SASSDOC_PATH public/
#  artifacts:
#    paths:
#      - public
#    expire_in: 30 days
